// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooskguttrqkltpkzoejd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vc2tndXR0cnFrbHRwa3pvZWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MDk0MzcsImV4cCI6MjA3ODk4NTQzN30.4ZTlv_3zemp1lFahlSKPIbm9m0QrpC6bJY20u9ACNhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});